[versions]
api-validator = "0.13.2"
build-config = "3.1.0"
dokka = "1.8.20"
gradle-publish = "1.1.0"
gson = "2.10"
kotlin = "1.9.20"
kotlinx-serialization = "1.5.1"
ksp = "1.9.20-1.0.13"
spotless = "6.20.0"
vanniktech-maven-plugin = "0.25.3"

[libraries]
gradle-plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
api-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "api-validator" }
build-config = { id = "com.github.gmazzo.buildconfig", version.ref = "build-config" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
vanniktech-maven = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-plugin" }
